- name: Provision
  hosts: localhost
  connection: local
  tasks:
  - name: Install boto
    sudo: yes
    pip: name=boto

  - name: Create ec2 instance
    ec2: 
     aws_access_key: {access_key}
     aws_secret_key: {secret_key}
     key_name: bonus
     instance_type: t2.micro
     region: us-east-1
     image: ami-c8580bdf
     wait: yes
     group_id: sg-3c29a841
     vpc_subnet_id: subnet-5d92d677
     assign_public_ip: yes
     wait_timeout: 600
     count: 1
     instance_tags:
      Name: "bonus"
    register: ec2_instances

  - name: Add host to in-memory inventory
    add_host:
     hostname: "{{ec2_instances.instances[0].public_ip}}"
     groupname: ec2_instance
     ansible_ssh_user: ubuntu
     ansible_ssh_private_key_file: ./bonus.pem

  - name: Wait for port 22
    wait_for: 
     host: "{{ec2_instances.instances[0].public_ip}}"
     port: 22 
     state: started

- name: Setup
  hosts: ec2_instance
  sudo: yes
  
  vars:
   - home_dir: /home/ubuntu
   - app_dir: App
   - temp_dir: /tmp/

  tasks:
   - name: Install Packages 
     apt: name={{ item }} update_cache=yes state=latest
     with_items:
       - build-essential
       - npm
       - nodejs-legacy
       - git

   - name: Install forever
     npm: name={{ item }} global=yes state=present
     with_items:
       - forever

   - name: Clone git repo 
     git: 
      repo: https://github.com/CSC-DevOps/App.git 
      dest: "{{home_dir}}/{{app_dir}}"
     register: git_cloned

   - name: Install npm packages 
     npm:
      path: "{{home_dir}}/{{app_dir}}"
     
- name: Tasks 
  hosts: ec2_instance
  sudo: yes

  vars:
   - home_dir: /home/ubuntu
   - app_dir: App
   - temp_dir: /tmp/

  tasks:
   - name: Run webserver
     command: forever start "{{home_dir}}/{{app_dir}}/main.js" 8000
     
   - name: Security
     apt: name={{ item }} state=latest
     with_items:
      - bash
      - openssl
      - openssh-client
      - openssh-server

   - shell: ls -1 "{{temp_dir}}"
     register: contents

   - name: Cleanup
     file: 
      path: "{{ temp_dir }}{{ item }}" 
      state: absent
     with_items:
       - "{{ contents.stdout_lines}}"
